# Description:
#   - DeepSeek code review with GitHub Actions for Android projects

name: Android Code Review
on:
  pull_request_target:
    types:
      - opened      # Triggers when a PR is opened
      - reopened    # Triggers when a PR is reopened
      - synchronize # Triggers when a commit is pushed to the PR
      - labeled     # Triggers when a label is added to the PR
  # Also trigger on push to main branch for testing
  push:
    branches:
      - main
      - master

# fix: GraphQL: Resource not accessible by integration (addComment) error
permissions:
  pull-requests: write

jobs:
  setup-deepseek-review:
    runs-on: ubuntu-latest
    name: Code Review
    # Run on all PRs without label restriction
    # if: contains(github.event.pull_request.labels.*.name, 'ai review')
    env:
      CHAT_TOKEN: ${{ secrets.DEEPSEEK_TOKEN }} # 设置环境变量，这样Action可以自动使用它
    steps:
      # 首先检出代码 - PR事件
      - name: Checkout PR code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史以便比较变更
          ref: ${{ github.event.pull_request.head.sha }}  # 对于PR，检出PR的代码
          persist-credentials: false  # 不保存凭证
          
      # 首先检出代码 - Push事件
      - name: Checkout Push code
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史
          
      # 方法1：使用Action并通过环境变量传递令牌
      - name: DeepSeek Code Review for PR (Method 1)
        if: github.event_name == 'pull_request_target'
        uses: hustcer/deepseek-review@main
        with:
          pr-number: ${{ github.event.pull_request.number }}
          max-length: 50000
          model: 'deepseek-coder'
          base-url: 'https://api.deepseek.com/v1'
          # 不需要显式设置chat-token，它会自动使用环境变量CHAT_TOKEN
          sys-prompt: >
            As a senior Android developer, perform comprehensive code review with focus on Android best practices, security, performance, and code quality.
          
      # 方法2：直接使用命令行并通过参数传递令牌
      - name: DeepSeek Code Review for Push (Method 2)
        if: github.event_name == 'push'
        run: |
          npm install -g @hustcer/deepseek-review
          deepseek-review \
            --max-length 50000 \
            --model 'deepseek-coder' \
            --base-url 'https://api.deepseek.com/v1' \
            --token '${{ secrets.DEEPSEEK_TOKEN }}' \
            --sys-prompt "As a senior Android developer, perform comprehensive code review with focus on Android best practices, security, performance, and code quality."
